name: 'Install dependencies'
description: 'Set up Python and install Poetry'

runs:
  using: composite
  steps:
    - uses: step-security/harden-runner@v2
      with:
        disable-sudo: true
        egress-policy: block
        allowed-endpoints: >
          files.pythonhosted.org:443
          github.com:443
          install.python-poetry.org:443
          pypi.org:443  

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Load cached Poetry installation
      id: cached-poetry
      uses: actions/cache@v4
      with:
        path: |
          ~/.local-${{ matrix.python-version }}
          ~/.config-${{ matrix.python-version }}
        key: poetry-${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.python-version }}

    - name: Install Poetry
      if: steps.cached-poetry.outputs.cache-hit != 'true'
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
        virtualenvs-path: ~/.venv-${{ runner.os }}-${{ matrix.python-version }}
