name: 'Install dependencies'
description: 'Install Python library dependencies using Poetry'

runs:
  using: composite
  steps:
    - uses: pantos-io/ci-workflows/.github/actions/install-poetry@7b6f7155fd88f3f90662e54fb098d5d78ec43982
    
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      shell: bash
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --without dev --no-interaction --no-root
