name: 'Install dependencies'
description: 'Install Python library dependencies using Poetry'

runs:
  using: composite
  steps:
    #- uses: pantos-io/ci-workflows/.github/actions/install-poetry@v1
    - uses: juanmanuel-tirado/ci-workflows/.github/actions/install-poetry@PAN-1889-python-version-matrix
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv-${{ runner.os }}-${{ matrix.python-version }}
        key: venv-${{ runner.os }}-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      shell: bash
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --without dev --no-interaction --no-root
